# Generated by Django 6.0.7 on 2026-07-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("normalized_title", models.CharField(db_index=True, max_length=512)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("dummyjson", "DummyJSON"),
                            ("fakestoreapi", "FakeStoreAPI"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("title_raw", models.CharField(max_length=512)),
                ("is_available", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="catalog.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("price_date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_records",
                        to="catalog.storeproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "-date"],
                        name="catalog_pro_product_e355f6_idx",
                    )
                ],
                "unique_together": {("product", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["product"], name="catalog_sto_product_275355_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storeproduct",
            unique_together={("store", "external_id")},
        ),
        migrations.AddIndex(
            model_name="pricerecord",
            index=models.Index(
                fields=["store_product", "-price_date"],
                name="catalog_pri_store_p_492817_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricerecord",
            unique_together={("store_product", "price_date")},
        ),
    ]
