# Generated by Django 6.0.7 on 2026-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                ("rate_to_uah", models.DecimalField(decimal_places=6, max_digits=12)),
                ("rate_date", models.DateField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["currency_code", "-rate_date"],
                        name="currency_ex_currenc_2be4b3_idx",
                    )
                ],
                "unique_together": {("currency_code", "rate_date")},
            },
        ),
    ]
